### ISSUE TITLE
Error executing process > 'pipeline:runPlannotate'  Caused by:   Missing output file(s) `*annotations.bed` expected by process `pipeline:runPlannotate`

### ISSUE THREAD

**Issue by senidr** [epi2me-labs/wf-clone-validation#5]
![image](https://user-images.githubusercontent.com/93718470/174533197-526d3ca2-f306-4e33-81d0-10296d82b518.png)

Hi everytime i try to run this tool i keep getting the same error no matter what order of commands i use. 

Would you please be able to help me see what is going wrong.

Thanks

**Comment by sarahjeeeze** [comment]
Hi, I think our most recent release v0.2.0 should have fixed this.

**Comment by amijalis** [comment]
I'm getting the same error after the release. Any tips on how to point to the new database?

**Comment by zihengluo** [comment]
Hi, I downloaded the database from GitHub on 29th August 2022, but the same error still exists. I ran the pipeline on 31 plasmids and only one of them got this error
![Screen Shot 2022-08-29 at 5 28 29 pm](https://user-images.githubusercontent.com/92278842/187147758-0dfc64e2-e9bf-472c-bfd9-7405dc515023.png)
.

**Comment by zihengluo** [comment]
> 

Thanks! The new version solved the error.

**Comment by Emmanuel1032967** [comment]
Hello. I am getting the same error. I have the latest version of the database.
hecking fastq input.
executor >  local (457)
executor >  local (457)
[3f/549b55] process > fastcat (90)                       [100%] 93 of 93 ✔
[31/41fc70] process > pipeline:checkIfEnoughReads (93)   [100%] 93 of 93 ✔
[d2/f0d938] process > pipeline:assembleCore (53)         [100%] 53 of 53 ✔
[19/4191da] process > pipeline:lookup_medaka_model (1)   [100%] 1 of 1 ✔
[bd/c22ba7] process > pipeline:medakaPolishAssembly (53) [100%] 53 of 53 ✔
[71/119165] process > pipeline:downsampledStats (52)     [100%] 53 of 53 ✔
[54/0aac62] process > pipeline:findPrimers (53)          [100%] 53 of 53 ✔
[c6/b1874f] process > pipeline:medakaVersion             [100%] 1 of 1 ✔
[b0/8b9840] process > pipeline:getVersions               [100%] 1 of 1 ✔
[97/393825] process > pipeline:getParams                 [100%] 1 of 1 ✔
[c0/d78de9] process > pipeline:runPlannotate (1)         [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:inserts                   -
[-        ] process > pipeline:report                    -
[93/04e1fb] process > output (53)                        [100%] 53 of 53
ERROR ~ Error executing process > 'pipeline:runPlannotate (1)'

Caused by:
  Process `pipeline:runPlannotate (1)` terminated with an error exit status (141)

Command executed:

  if [ -e "assemblies/OPTIONAL_FILE" ]; then
      assemblies=""
  else
      assemblies="--sequences assemblies/"
  fi
  workflow-glue run_plannotate $assemblies --database wf-clone-validation-db

Command exit status:
  141

Command output:
  (empty)

Work dir:
  /home/grid/work/c0/d78de9af665fbc5cb7461322ca94de

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Comment by sarahjeeeze** [comment]
Hi, did you run this cmd before the workflow? 
```
wget https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-clone-validation/wf-clone-validation-db.tar.gz
tar -xzvf wf-clone-validation-db.tar.gz

**Comment by Emmanuel1032967** [comment]
Hello. I did

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sarahjeeeze** [comment]
Hi, I need to investigate but have you tried running it without the `db_directory` parameter? The DB is now already included with the plannotate package.

**Comment by sarahjeeeze** [comment]
Closing as no response but should also be fixed in the newer versions of the workflow as the db_directory input parameter no longer required.
